# Generated by Django 6.1 on 2026-09-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='comment',
        ),
        migrations.AddField(
            model_name='verification',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
