# Generated by Django 6.1 on 2026-08-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
