# Generated by Django 5.2.17 on 2026-09-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_country_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_type',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('TRAINING', 'Training'), ('PROJECT', 'Project'), ('OTHER', 'Other'), ('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], max_length=20),
        ),
    ]
