# Generated by Django 5.2.17 on 2026-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_travelrequest_travel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('DOCUMENT_PENDING', 'Document Pending'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('MANAGER_APPROVAL', 'Manager Approval'), ('MANAGER_APPROVED', 'Manager Approved'), ('TRAVEL_BOOKING', 'Travel Booking'), ('TRAVEL_BOOKED', 'Travel Booked'), ('TRAVEL_IN_PROGRESS', 'Travel In Progress'), ('EXPENSE_SUBMISSION', 'Expense Submission'), ('EXPENSE_VERIFICATION', 'Expense Verification'), ('SETTLEMENT_PENDING', 'Settlement Pending'), ('SETTLEMENT_APPROVAL', 'Settlement Approval'), ('SETTLEMENT_APPROVED', 'Settlement Approved'), ('SETTLEMENT_PROCESSING', 'Settlement Processing'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('DOCUMENTS_UNDER_REVIEW', 'Documents Under Review'), ('VISA_PROCESSING', 'Visa Processing'), ('VISA_APPROVED', 'Visa Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_CANCELLED', 'Request Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
