# Generated by Django 5.2.17 on 2026-09-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("travel", "0006_alter_travelrequest_status"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NOT_APPLIED", "Not Applied"),
                            ("APPLIED", "Applied"),
                            ("UNDER_PROCESS", "Under Process"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Country the visa is applied for. "
                            "Defaults to the destination "
                            "country name."
                        ),
                        max_length=100,
                    ),
                ),
                (
                    "applied_on",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "decision_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        default="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visa_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "travel_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa",
                        to="travel.travelrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa",
                "verbose_name_plural": "Visas",
            },
        ),
    ]
