# Generated by Django 6.1 on 2026-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
