# Generated by Django 6.1 on 2026-08-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='maximum_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
