# Generated by Django 6.1 on 2026-08-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentrequirement_maximum_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
