# Generated by Django 6.1 on 2026-08-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentrequirement_updated_at'),
        ('travel', '0003_travelrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel.travelrequest'),
        ),
    ]
