# Generated by Django 5.0.14 on 2026-09-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('REVIEWER', 'Reviewer / HR'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('REVIEWER', 'Reviewer'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='EMPLOYEE', help_text='Legacy single-role field kept for backward compatibility. Authorization uses `roles`.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.role'),
        ),
    ]
