# Generated by Django 5.2.17 on 2026-09-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("travel", "0006_alter_travelrequest_status"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=60),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "previous_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "travel_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="travel.travelrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log entries",
            },
        ),
    ]
